export const CONTENT = {
    DebitCard: 'Debit Card',
    AvailableBalance: 'Available Balance',
    S$: 'S$',
    Show: 'Show',
    Hide: 'Hide',
    CardNumber: 'card number',
    Thru: 'Thru:',
    CVV: 'CVV:',
    DebitSpendLimit: 'Debit card spending limit',
    TopUp: 'Top-up account',
    WeeklySpendingLimit: 'Weekly spending limit',
    FreezeCard: 'Free card',
    GetANewCard: 'Get a new card',
    DeActivatedCards: 'DeActivated cards',
    SpendingLimit: 'Spending limit',
    SetAWeekly: 'Set a weekly debit card spending limit',
    HereWeeklyMeans: 'Here weekly means the last 7 days not the calendar week',
    Save: 'Save',
    Home: 'Home',
    DebitCard: 'Debit Card',
    Payment: 'Payment',
    Credit: 'Credit',
    Profile: 'Profile',
    $: '$',
    DepositMoney: 'Deposit money to your account to use with card',
    YourWeekly: 'Your weekly spending limit is S$ 5,000',
    YourDebit: 'Your debit card is currently active',
    ThisDeactivates: 'This deactivates your current debit card',
    YourPreviously: 'Your previously deactivated cards',
  }